http:
  addr: :8000
  auth:
    username: "alertmanager"
    password: "verysecure"
ntfy:
  url: https://ntfy.sh/booyah
  priority: urgent
  # List of emoji shortcodes: https://docs.ntfy.sh/emojis/
  tags:
    - tag: "+1"
      condition: status == "resolved"
    - tag: rotating_light
      condition: status == "firing"
  templates:
    title: |
      {{if eq .Status "resolved" }}Resolved: {{ end }}{{ index .Annotations "summary" }}
    description: |
      {{ index .Annotations "description" }}
  auth:
    username: "admin"
    password: "verysecure"
